Feature/r4 su 29 canvas new
Hellga2023/Shooter pull request #21
Opened 2023-09-04 06:33 UTC by Hellga2023

### Какую задачу решаем

Создание страницы игры. 
Создание игрового движка. 
Создание типов для игры. Три вида врагов и игрок.
Создание основного цикла игры. 
Отрисовка врагов, их движения, создание траектории движения врагов на текущем уровне (работает неплохо, но есть некоторые необработанные крайние случаи), добавление возможности движения нескольких игроков одного типа по одной траектории, отрисовка игрока, добавление возможности выстрела игроком, добавление возможности движения игроком. Добавление возможности начинать игру заново и останавливать игру (работает но с багом). Добавление конца уровня и конца игры (сейчас это работает с багом).

### Скриншоты/видяшка (если есть)
[Запись экрана от 2023-08-18 11.25.10.webm](https://github.com/Hellga2023/29CohortGame/assets/126746758/2de4a274-8457-4e27-933f-8ef091f653d5)

### TBD (если есть)

Доработка движения врагов - учитывать размеры кадра в спрайте, чтобы корабль не уходил за пределы поля игры.

Доработка рассчета координат - учитывать отступы внутри кадра до корабля чтобы рассчитывать коллизии, учитывать отступы внутри кадра до корабля чтобы рассчитывать начальную точку выстрела.

Добавление возможности стрелять врагам.

Пофиксить баг остановки игры.

Пофиксить баг когда стартуем игру заново.

Пофиксить баг конца уровня и конца игры.

Доработать траекторию движения врагов.

2023-09-06 07:32 UTC, SoluyanovKonstantin approved these changes
апрув, было сделано много работы

2023-09-07 06:21 UTC, Olegas requested changes
Добрый день.
Выглядит здорово но написано запутано.
Написал комментарии что можно поправить и на что обратить внимание.
В целом общее замечание - классы используются как-то очень странно: static там где он не нужен, несколько разных объектов смешаны в один класс с множеством вилок внутри, поведение внедряется через конструктор там где это не нужно (или я как минимум не понял зачем именно так сделано)

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/collisionManager.ts
> +        // if player is undefined detect ships collision with player rocket and set enemy exploiding
Сложно. Я завис уже на этапе чтения комментария. Лучше разделить на две функции - каждая под свою задачу. Если внутри есть общая логика - ее можно вынести куда-то и переиспользовать (что бы не дублировать код)

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/collisionManager.ts
> +                const shipY = ship.state.coordinates.y;
ship.state уже вынесен в переменную. А еще, если использовать деструктуризацию, может получиться короче и более читаемо (хотя тут есть доля субъективности)
```
const { x: shipX, y: shipY } = shipState.coordinates;
```

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +    constructor(ctx: CanvasRenderingContext2D) {
Если реализуется паттерн Singleton, то конструктор лучше сделать приватным и добавить `public static getInstance()` который уже отдает имеющийся или создает новый. Поле instance делается приватным

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +            const player = state.ships.find(ship => +ship.type === ShipType.Player);
Вот этот поиск корабля игрока повторяется многократно. Можно сделать на объекте, который описывает состояние игры, метод getPlayer и использовать его. Так будет меньше дублирования кода.

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/objectAnimator.ts
> +        CollisionManager.collisionDetection();
Выглядит странно (с архитектурной точки зрения) что объект, отвечающий за анимацию, так же знает о каких-то столкновениях

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/objectAnimator.ts
> +        if (+(playerShip?.state as TShipState).liveState === LiveState.Dead) {
А зачем ты каждый раз делаешь приведение к числу при сравнении liveState с возможными значениями? Может быть тип как-то не правильно описан если такое приходится делать?

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/objectAnimator.ts
> +            this.drawLevelEnd();
Судя по этому вызову и вызову детекции столкновений, этот объект совсем не аниматор, он скорее всем состоянием игры управляет

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/store/mockGameState.ts
> +    private static initPlayer = () =>
Зачем этот метод сделан static? Он ведь используется только внутри экземпляра класса и не имеет смысла снаружи класса без его экземпляра.

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/collisionManager.ts
> +        y: number,
У вас есть тип TPoint - не лучше его сюда передавать одним аргументом? А что бы в коде не разбирать на две переменные, можно использовать деструктуризацию в аргументах
```
detect({ x, y }: TPoint, ...)
```

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    [ShotType.Player]: { ...shotParams, ...{ image: PlayerRocketImage } },
Тут создается объект и сразу же "разбирается" что бы скопировать в другой объект.
Проще вот так:
```
{ ...shotParams, image: RocketImage }
```

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    ) {
Достаточно странный объект с архитектурной точки зрения. Смотри, при таком конструкторе никто не запретит создать объект с isShip = false но при этом указать type:  ShipType. 
По хорошему тут надо или несколько объектов делать с наследованием от базового или как-то опции описывать иначе.

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +        }
Если весь код прошит условиями - ship или не ship - верный признак что надо на два объекта делить

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    updateState: (time: number, shouldChangeFrame: boolean, direction?: TDirection) => void;
Вот это же настоящий метод класса. Зачем его объявлять как свойство и затем заполнять в конструкторе. Еще у других объектов видел такой же паттерн (метод updateStateFunction). Надо сделать обычный метод и все

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +        this.updateStateFunction = updateStateFunction; // todo this instead of frameCount??
Странно. Для чего передавать функцию обновления состояния в конструктор через параметры? Она может быть разная у объектов одного типа?

2023-09-07 06:21 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/trajectory.ts
> +    public static shouldSwitchSegment = (time: number, length: number): boolean => time >= length;
Вот этот метод не понятно зачем сделан public static. Разве он используется где-то снаружи класса?

2023-09-08 07:33 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +    constructor(ctx: CanvasRenderingContext2D) {
Для меня сложность в том, что для движка нужен CanvasRenderingContext2D. Сделала его аргументом в getInstance(CanvasRenderingContext2D) и выбрасываю ошибку если нет ни instance ни передан контекст. Не уверена правильное ли это решение, буду благодарна за фидбек

2023-09-08 07:38 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +            const player = state.ships.find(ship => +ship.type === ShipType.Player);
Круто, люблю когда можно сократить код, спасибо за подсказку, сделала

2023-09-08 17:26 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/collisionManager.ts
> +        // if player is undefined detect ships collision with player rocket and set enemy exploiding
Принято, постаралась упростить логику, метод для колизий плеера и врагов разбила на 2 с более понятными названиями.

2023-09-08 17:28 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/collisionManager.ts
> +                const shipY = ship.state.coordinates.y;
Классная запись, не знала что так можно. После рефакторинга эти строчки убрала и даже жалко, возьму теперь на заметку, спасибо!

2023-09-08 17:31 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +            const player = state.ships.find(ship => +ship.type === ShipType.Player);
UPD. Поняла что рациональней хранить отдельно корабль игрока и врагов, т.к. много где все равно их отделяю и появляются лишние проверки. Сделала два поля у стейта enemies и player

2023-09-08 17:34 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/objectAnimator.ts
> +        CollisionManager.collisionDetection();
У меня сомнения что objectAnimator и есть gameEngine, беру мысль на подумать, пока не поняла как бы правильно разграничить логику

2023-09-08 17:44 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/store/mockGameState.ts
> +    private static initPlayer = () =>
убрала static

2023-09-08 17:48 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/collisionManager.ts
> +        y: number,
Порефакторила весь код CollisionManager вроде теперь попроще стало, и TPoint использую

2023-09-08 18:06 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    [ShotType.Player]: { ...shotParams, ...{ image: PlayerRocketImage } },
поправила

2023-09-09 07:50 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/collisionManager.ts
> +        // if player is undefined detect ships collision with player rocket and set enemy exploiding
UPD. перепилила все типы, CollisionManager тоже теперь стал понятнее и проще

2023-09-09 07:52 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/objectAnimator.ts
> +        if (+(playerShip?.state as TShipState).liveState === LiveState.Dead) {
Убрала приведение, на каком-то этапе там был баг, но сейчас не вижу его.

2023-09-09 07:54 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/objectAnimator.ts
> +            this.drawLevelEnd();
пока переименовала в GameStateManager. Не вижу сейчас возможности разделить логику анимации и состояния игры, на каждой итерации анимации я проверяю параметры (умер ли игрок, закончился ли уровень) и ставлю нужное состояние.

2023-09-09 07:57 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    [ShotType.Player]: { ...shotParams, ...{ image: PlayerRocketImage } },
UPD. перепилила типы, в параметром теперь конструктором создаются эти обьекты. Но теперь буду иметь ввиду чтобы не городить лишних действий, спасибо!

2023-09-09 07:58 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    ) {
Перепилила все типы, теперь стало гораздо понятней кмк, постаралась сделать так чтобы каждый за свое состояние отвечал

2023-09-09 07:58 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +        }
сделано

2023-09-09 07:59 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    updateState: (time: number, shouldChangeFrame: boolean, direction?: TDirection) => void;
сделано

2023-09-09 08:00 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +        this.updateStateFunction = updateStateFunction; // todo this instead of frameCount??
да, была разная, теперь сделала новые типы и updateState методы для них

2023-09-09 08:01 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/trajectory.ts
> +    public static shouldSwitchSegment = (time: number, length: number): boolean => time >= length;
не используется, поправила

2023-09-09 08:27 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/trajectory.ts
> +    public static shouldSwitchSegment = (time: number, length: number): boolean => time >= length;
Поправила по всем замечаниям, код получился более читаемым и простым, спасибо за такое подробное ревью! Очень нравится как код эволюционирует. Отправляю на новое ревью, буду благодарна за обратную связь, здорово будет узнать все ли правильно ли поняла и смогла исправить, действительно ли стало лучше и читаемей не только мне как автору

2023-09-09 09:57 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/objectAnimator.ts
> +            this.drawLevelEnd();
UPD. вернула аниматор в названии. Вынесла в моковый стейт, глобальный стейт игры (loaded, levelStarted, paused, ended) и теперь внутри gameEngine обрабатываю эти состояния. Аниматор управляет стейтом. Пока придумала так эту логику разграничить. Возможно есть лучший способ, но пока его не вижу. Буду благодарна за подсказки

2023-09-09 14:16 UTC, Olegas requested changes
Огонь! Стало супер понятнее!
Но есть еще что поменять. Написал подробные комментарии. Давай чуть дополируем и будет конфета.

2023-09-09 14:16 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    public getState = () => this.state as ShipState;
В классе DrawableGameObject уже есть такой метод. Отсюда можно удалить

2023-09-09 14:16 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    public getState = () => this.state as ShotState;
В классе DrawableGameObject уже есть такой метод. Отсюда можно удалить

2023-09-09 14:16 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/store/mockRedux.ts
> +class MockRedux {
Почему это MockRedux? Это ведь состояние игры. При чем тут Mock и при чем Redux?
Mock это что-то не настоящее. Тут же вполне себе нормальный объект состояния. Redux это название библиотеки, технологии организации состояния приложения. Тут даже близко ничего нет от Redux. Я бы назвал просто GameState - сразу все понятно

2023-09-09 14:16 UTC, Olegas commented on packages/client/src/app/pages/game/game.tsx
> +        window.addEventListener('keydown', onKeyDown);
Тут что-то не то. Подписка есть, отписки нет. Это проблема.
Я бы сделал state с признаком запущена игра или нет. Дальше бы сделал от этого состояния зависимый useEffect в котором бы ставил подписку, а в деструкторе эффекта - отписывался от события. В результате при остановке игры и при разрушении компонента будет отписка от события.

2023-09-09 14:16 UTC, Olegas commented on packages/client/src/app/pages/game/game.tsx
> +            GameEngine.getInstance(context);
Если GameEngine не делать синглтоном и сложить его в ref, то ему можно сделать метод - setCanvas, он его внутри сохранит и будет брать от него getContext('2d') когда это будет нужно. И не придется делать getInstance с аргументом.

2023-09-09 14:16 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/store/mockRedux.ts
> +        GameEngine.getInstance().processNewGameState();
А здесь не надо использовать синглтон вообще. На сколько я вижу, все вызовы setState идут из Game. Этот же компонент (Game) владеет GameEngine. Пусть он каждый раз просто при вызове setState сразу же рядом вызывает processNewGameState у GameEngine и тогда тут не придется использовать getInstance и вообще состояние игры не будет ничего знать про движок (что в целом логично)
Скорее наоборот. Движок знает о состоянии. У движка есть метод - переключи состояние. Он переключает состояние и делает то что ему нужно (то что сейчас в processNewGameState)

2023-09-09 16:48 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    public getState = () => this.state as ShipState;
Оставила private метод getShipState, чтобы не повторять логику приведения типа.

2023-09-09 16:48 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +    public getState = () => this.state as ShotState;
сделано

2023-09-09 16:49 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/store/mockRedux.ts
> +class MockRedux {
Думала, что прикрутим редакс и сделаем слайс для игры, куда все это перенесем. Вернула название gameState

2023-09-09 17:08 UTC, Hellga2023 commented on packages/client/src/app/pages/game/game.tsx
> +            GameEngine.getInstance(context);
Не совсем поняла, что нужно сделать. Поясни пожалуйста, поподробнее

2023-09-09 17:32 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/store/mockRedux.ts
> +        GameEngine.getInstance().processNewGameState();
Да, так логичнее, движок переключает стейт. Сделала метод в движке setGameState и там же обрабатываю новый стейт. Но дальше у меня затык. Game.tsx вызывает setGameState, тут все норм. А вот gameAnimator при прогоне цикла смотрит умер ли игрок (это мы можем узнать в цикле после апдейта состояния игрока и расчета всех коллизий) и закончился ли уровень (сравниваем текущее время с длиной уровня) - обе эти проверки выставляют новый стейт (gameEnded|levelEnded). Вроде бы надо вынести эту логику, но не вижу как. Стоит здесь копать или пока оставить как есть?

2023-09-09 17:34 UTC, Hellga2023 commented on packages/client/src/app/pages/game/game.tsx
> +        window.addEventListener('keydown', onKeyDown);
Правильно понимаю, нужно у gameState сделать поле isGameRunning и подписать на него useEffect? Вроде такого:

```
useEffect(() => {
       ... some code here ...
    }, [isGameRunning]);
```

2023-09-10 17:11 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/store/mockRedux.ts
> +        GameEngine.getInstance().processNewGameState();
У нас какая-то беда с историей гита в деве, сейчас замержилась в свою ветку и вижу кучу изменений не из моей задачи, сорри пока не нашла как это пофиксить, работаю над этим

2023-09-11 12:45 UTC, Hellga2023 commented on packages/client/src/app/pages/game/game.tsx
> +        window.addEventListener('keydown', onKeyDown);
Создала новую ветку из-за бага с историей. Решила эту задачу там через redux

2023-09-11 12:46 UTC, Hellga2023 commented on packages/client/src/app/pages/game/game.tsx
> +            GameEngine.getInstance(context);
Тут так и не поняла до конца что нужно сделать, т.к. gameEngine передает контекст в gameAnimator. Не поняла как это сделать если не при создании gameEngine

2023-09-12 14:30 UTC, closed without merging