Feature/r4su 25 layout users page
Hellga2023/Shooter pull request #23
Opened 2023-09-04 13:49 UTC by mccorn

### Какую задачу решаем
https://linear.app/andrew-markeev/issue/R4SU-25/layout-users-page

ОР:
Страница с информацией о пользователе, возможностью загрузить и сменить аватар, изменить пароль

PS В рамках этой задачи добавлены два компонента (lazyInput, lazyForm), а также добавлен функционал на страницах Signin и Signup

### Скриншоты/видяшка (если есть)
![image](https://github.com/Hellga2023/29CohortGame/assets/25058662/dd2e1374-ec93-433d-8534-f4309fc8800e)

PS 
Это дубликат пр. Апрув получен в рамках https://github.com/Hellga2023/29CohortGame/pull/14

2023-09-04 14:00 UTC, SoluyanovKonstantin approved these changes

2023-09-05 17:21 UTC, Olegas requested changes
Добрый день.
Есть замечания, нужно доработать.

2023-09-05 17:21 UTC, Olegas commented on packages/client/src/app/api/UserAPI.ts
> +        const reqOptions = Object.assign(options, {
Не надо так делать, тут ошибка. Каждый раз assign присваивает новые опции в объект, указанный в первом аргументе. А там у вас глобальная переменная. Каждый следующий вызов будет добавлять опции в этот глобальный объект. 
Зачем вообще тут assign? У вас же там изначально пустой объект. Почему просто не написать reqOptions = { headers: ..., data: ... }

2023-09-05 17:21 UTC, Olegas commented on packages/client/src/app/api/UserAPI.ts
> +    // }
Не надо оставлять закомментированный код в проекте

2023-09-05 17:21 UTC, Olegas commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +    wrapType?: 'line' | 'row' | string;
Этот параметр затем идет в компонент LazyInput. Там у него тип string. Зачем тут line или row?

2023-09-05 17:21 UTC, Olegas commented on packages/client/src/app/pages/profile/profile.tsx
> +            alert((response as TResponse)?.status);
Зачем во всех вызовах alert? Я понимаю для отладки - да, но когда это уже готовое решение, хотя бы убрать это в консоль, если уж надо смотреть на то, что вернулось. А по хорошему для этого есть DevTools и вкладка Network там.

2023-09-05 17:21 UTC, Olegas commented on packages/client/src/app/pages/profile/profile.tsx
> +                    <div className="row stretch" />
Две одинаковые пустые строки? Зачем это? Выглядит как будто забыли убрать что-то.

2023-09-05 17:21 UTC, Olegas commented on packages/client/src/app/pages/profile/profile.tsx
> +                        ]}>
Значения для параметра inputs лучше собрать в useMemo, иначе они будут каждый раз новые и будут заставлять форму каждый раз перерисовываться.

2023-09-06 09:10 UTC, mccorn commented on packages/client/src/app/pages/profile/profile.tsx
> +            alert((response as TResponse)?.status);
Это не для отладки, а временное решение, пока мы не сделаем свои модальные окна и авторедиректы

2023-09-06 10:07 UTC, mccorn commented on packages/client/src/app/pages/profile/profile.tsx
> +            alert((response as TResponse)?.status);
Это не для отладки, а временное решение, пока мы не сделаем свои модальные окна и авторедиректы

2023-09-06 14:52 UTC, Olegas commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +export const memoAll = (array: IInputData[]) => array.map(node => memo(node));
Я бы так не делал. Тут получилось, что в компоненте использование memoAll не выглядит как хук. А значит не понятно другим разработчикам, не подвергается статическом анализу и линтерам что может привести к ошибкам. 
Если что-то использует хуки - оно должно быть либо хуком (начинаться с use) либо быть компонентом (называться с большой буквы)

2023-09-06 14:53 UTC, Olegas requested changes
Есть проблема с memoAll - написал там отдельный комментарий.
Надо переделать

2023-09-06 16:22 UTC, mccorn commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +export const memoAll = (array: IInputData[]) => array.map(node => memo(node));
Из ваших слов не совсем понятно, достаточно ли будет просто поменять имя функциям, чтобы они стали хуками или нет?

2023-09-07 08:55 UTC, mccorn commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +export const memoAll = (array: IInputData[]) => array.map(node => memo(node));
И почему нельзя передать например хук в метод вроде такого

```
condt forAll = (arr, callback) => arr.map(
  node => callback(node[0], node[1])
)

Применение:
forAll(
  [ {name: 'login', value: login, handler: setLogin}, [login] ]
  useMemo,
)
```

2023-09-07 19:11 UTC, Olegas commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +export const memoAll = (array: IInputData[]) => array.map(node => memo(node));
Расскажу в чем тут проблема.
В [документации React](https://ru.react.js.org/docs/hooks-rules.html) написано - Only Call Hooks at the Top Level, Don’t call Hooks inside loops, conditions, or nested functions

То есть приведенный подход в первую очередь нарушает правила использования хуков. 

За этим правилом стоит основная штука для хуков - они всегда должны вызываться в одном и том же порядке и в одном и том же количестве (в рамках компонента). 

Еще одна проблема с memoAll в том, что массив с результатом useMemo не то же самое, что useMemo для массива. memoAll каждый раз все равно делал новый массив, хоть даже и с одинаковыми элементами. Но с точки зрения сравнения значений пропсов массивы будут разными. React на заглядывает внутрь массивов, он сравнивает их "по ссылке".

Еще такой memoAll маскирует потенциальную проблему - изменится количество данных в массиве - изменится количество вызванных хуков. А значит будет нарушено требование документации

2023-09-07 19:12 UTC, Olegas commented on packages/client/src/app/pages/profile/profile.tsx
> +                            [login, displayName, firstName, secondName, email, phone]
Да, вот так теперь правильно. Я бы еще в переменную вынес что бы читалось лучше.

2023-09-07 19:12 UTC, Olegas commented on packages/client/src/app/pages/profile/profile.tsx
> +                        ]}>
Здесь та же проблема, тоже нужен useMemo

2023-09-07 19:12 UTC, Olegas approved these changes
Работу принимаю. Оставил пару комментариев что можно еще немного улучшить.

2023-09-07 19:47 UTC, mccorn commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +export const memoAll = (array: IInputData[]) => array.map(node => memo(node));
Это не приятно, понимать, какую проблему надо решить уже после того, как случайно её решил, потратив много времени на ожидания ответов на комментарий и перебор всех мест в небе, куда можно ткнуть. Обернуть весь массив в useMemo было лишь удачной догадкой.

2023-09-08 06:14 UTC, Olegas commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +export const memoAll = (array: IInputData[]) => array.map(node => memo(node));
@mccorn Справедливое замечание, мне стоило сразу более подробно изложить проблему. Извиняюсь.

2023-09-08 06:55 UTC, mccorn commented on packages/client/src/app/components/lazy/lazyForm/lazyForm.tsx
> +export const memoAll = (array: IInputData[]) => array.map(node => memo(node));
@Olegas спасибо, извинения приняты

2023-09-08 06:57 UTC, merged