Feature/r4su 35 implement game mechanics
Hellga2023/Shooter pull request #25
Opened 2023-09-09 14:53 UTC by SoluyanovKonstantin

### Какую задачу решаем
https://linear.app/andrew-markeev/issue/R4SU-35/implement-game-mechanics

### Скриншоты/видяшка
![demo](https://github.com/Hellga2023/29CohortGame/assets/60567325/baa44f43-44f2-4cd6-9c77-3e0eb750859e)

2023-09-09 16:28 UTC, mccorn reviewed
Давай почистим консоли и избавимся от магических чисел. В остальном все хорошо, спасибо

2023-09-09 16:28 UTC, mccorn commented on packages/client/src/app/pages/game/game.tsx
> +            (ev.nativeEvent as MouseEvent).clientY - (ev.target as HTMLElement).offsetTop - 30;
Что за числа 35 и 30? Не стоит ли вынести их в константы?

2023-09-09 16:28 UTC, mccorn commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +                        y: Math.min(coordinates.y + step, params.WIDTH - 64),
Снова магические числа. Понимаю, что наследие, но давай избавимся

2023-09-09 16:36 UTC, Hellga2023 reviewed
Оставила пару замечаний исходя из опыта ревью своей ветки.

2023-09-09 16:36 UTC, Hellga2023 commented on packages/client/src/app/pages/game/game.tsx
> +        shootInterval = setInterval(() => {
Этот метод по логике относится к игре, возможно стоит убрать в gameEngine? Сейчас получается что логика стрельбы в реакт компоненте.

2023-09-09 16:36 UTC, Hellga2023 commented on packages/client/src/app/pages/game/game.tsx
> +                    onMouseMove={handleMouseMove}
Возможно стоит завязать обработку движения мыши на состояние когда игра в процессе? Пишу, потому что сейчас в своей ветке как раз поправляю замечание ревьюера, где он предлагает подписываться на событие когда игра стартует и отписываться если игра на паузе или закончена, либо если компонент разрушился.

2023-09-09 16:45 UTC, Hellga2023 commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +    // eslint-disable-next-line class-methods-use-this
кстати классно, что пишешь какой именно рул игнорится в каждом случае, наглядно. Возьму на заметку

2023-09-09 17:17 UTC, SoluyanovKonstantin commented on packages/client/src/app/pages/game/game.tsx
> +                    onMouseMove={handleMouseMove}
Внутри отбработчика проверяется что игра началась и не на паузе

2023-09-09 17:19 UTC, SoluyanovKonstantin commented on packages/client/src/app/pages/game/game.tsx
> +        shootInterval = setInterval(() => {
Логика того когда идет стрельба по-моему должна быть вне движка так как это относится к сценарию игрового процесса

2023-09-09 17:28 UTC, mccorn approved these changes

2023-09-10 08:47 UTC, IvanPeleshok commented on packages/client/src/app/pages/game/game.tsx
> +        shootInterval = setInterval(() => {
@SoluyanovKonstantin, самый правильный вариант - вынести всю логику игры и логику обработки клавиш в отдельный модуль
Непосредственно в компоненте дёргаем методы в нужных местах

Таким образом, легко тестировать, легко читать и модифицировать

2023-09-10 08:49 UTC, IvanPeleshok commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +                direction += 'Up';
Up / Down и тд можно бы было вынести в константы или перечисление
И переиспользовать в других местах, если такие значения применяются

2023-09-10 08:50 UTC, IvanPeleshok commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +                        y: Math.min(coordinates.y + step, params.WIDTH - shipSize),
Круто, что избавляетесь от волшебных чисел

2023-09-10 08:51 UTC, IvanPeleshok commented on packages/client/src/app/pages/game/gameEngine/types/gameTypes.ts
> +                case 'UpLeft':
Аналогично, можно бы было вынести в константы значения условий Left / UpLeft / Right и тд

2023-09-10 08:51 UTC, IvanPeleshok commented on packages/client/src/utils/index.ts
> +const getcookie = (a: string) => {
getCookie

2023-09-10 08:55 UTC, IvanPeleshok commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +                approximatelyEqual(playerX, mouseX, 2) &&
Рекомендация: лучше такие условия в следующем формате писать
```
if (
  var1
  && var2
  && var3
) {
```

2023-09-10 08:56 UTC, IvanPeleshok requested changes
Классная работа, всё выглядит прекрасно, но есть небольшие замечания

2023-09-10 11:44 UTC, SoluyanovKonstantin commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +                approximatelyEqual(playerX, mouseX, 2) &&
у нас линтер так настроен https://eslint.org/docs/latest/rules/operator-linebreak

2023-09-10 11:54 UTC, SoluyanovKonstantin commented on packages/client/src/app/pages/game/game.tsx
> +        shootInterval = setInterval(() => {
у нас еще скорее всего будут задачи на рефактор, мы собирались собраться в пн и обсудить проект, в том числе архитектуру обсудим, это предложение озвучу там, оно весьма полезно, но в рамках задачи мне кажется лишним вводить новую сущность пока еще не обо всем договорились

2023-09-10 13:52 UTC, IvanPeleshok commented on packages/client/src/app/pages/game/game.tsx
> +        shootInterval = setInterval(() => {
Если будет обсуждение - то не вижу проблем :)
Найдите на это время, важная часть дальнейшей работы

2023-09-10 13:54 UTC, IvanPeleshok commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +                approximatelyEqual(playerX, mouseX, 2) &&
@SoluyanovKonstantin, понял :)
Возможно, очень субъективно, но было бы удобнее, если логические и математические операторы при переносе были бы вначале, т.к в конце они могут попросту затеряться, что приведёт к неприятным последствиям (бажкам)

2023-09-10 13:55 UTC, IvanPeleshok approved these changes
Всё понравилось
Замечательная работа!

Есть что обсудить с командой - предлагаю записать это в тех.долг

Апрув

2023-09-13 15:32 UTC, closed without merging