Подключение тестов
Hellga2023/Shooter pull request #29
Opened 2023-09-11 08:28 UTC by Nikolai56

### Какую задачу решаем

Fixes R4SU-41
https://linear.app/andrew-markeev/issue/R4SU-41/add-tests-for-game

Добавляем тесты на игровой движок (Engine, Ship, Trajectory) и один UI.

p.s. Нарочно изменена (нарушена) инкапсуляция

2023-09-11 18:45 UTC, SoluyanovKonstantin approved these changes

2023-09-11 18:45 UTC, SoluyanovKonstantin commented on packages/client/src/tests/index.test.ts
> +        // console.log('g', g);
комменты почистить

2023-09-12 07:22 UTC, mccorn commented on packages/client/src/tests/index.test.ts
> +        // console.log('g', g);
Точнее весь файл убрать)

2023-09-12 17:23 UTC, Olegas requested changes
Получились странные тесты, которые тестируют закрытые автором детали реализации. Написал подробные комментарии.

2023-09-12 17:23 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/tests/gameShip.test.ts
> +describe('Тесты gameEngine', () => {
Здесь тестируется не GameEngine. Надо поменять название

2023-09-12 17:23 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/types/trajectory.ts
> +    static getSegmentLength = (startPoint: TPoint, endPoint: TPoint): number =>
Это странно. Разработчик класса явно указал - это деталь не является публичным API. А следовательно не должна тестироваться. Есть публичные методы. Именно с ними взаимодействуют потребители. Значит именно их и надо тестировать. getSegmentLength будет часть внутренней реализации.

2023-09-12 17:23 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/tests/gameShip.test.ts
> +    });
Эти тесты не понятно что тестируют. Обычно проверять надо логику. Т.е. есть класс, мы делаем с ним какое-то действие и он как-то реагирует. Вызывает функцию, создает событие, меняет внутреннее состояние которое можно проверить через публичные свойства или методы.

2023-09-12 17:23 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/tests/gameEngine.test.ts
> +        expect(gameEngine.animator.start()).toBe(resultStart);
Не понятно для чего делать проверку того, что подмененный метод возвращает подмененный результат. Самой проверки что методы были вызваны - уже достаточно

2023-09-12 17:23 UTC, Olegas commented on packages/client/src/app/pages/game/gameEngine/gameEngine.ts
> +    pause = () => {
Еще одно место, где разработчик явно указал - это приватная деталь. А тут она специально открыта. Тестировать нужно публичное API.

2023-09-12 17:35 UTC, mccorn commented
@Olegas а вы еще дольше делайте свою работу, и к тому времени как будут написаны тесты проект уже сделают. Отстаньте от меня и просто зачтите результат понимания темы, потому что пока вы баклуши бьете, код, который я покрываю тесты меняются. Если вы отказываетесь вести себя адекватно ситуации, я требую смены ревьюера.

2023-09-12 17:41 UTC, Olegas commented
@mccorn С вопросом смены ревьюера прошу обратиться к вашему куратору. К сожалению работу принять не могу, т.к. задача сделана не правильно

2023-09-12 17:42 UTC, mccorn commented
@Olegas обоснуйте

2023-09-12 17:45 UTC, Olegas commented
@mccorn Основные замечание: тестируются детали реализации а не публичное API.
К сожалению тесты к старой версии движка я проверить не мог, т.к. в PR была куча изменений и не было никак обозначено какие комиты тестировать.

2023-09-12 17:48 UTC, mccorn commented
@Olegas могли, но не стали. По истории хорошо было видно, какие коммиты от меня и про тесты

2023-09-12 18:04 UTC, Olegas commented
@mccorn задача ревьюера на проекте не только проверить код, но и способствовать развитию правильных практик. Делать PR, в котором перемешано несколько задач от разных людей - не правильно. Не правильно не только в Практикуме, но и в реальных проектах.
Если вы не согласны с моим подходом - ваше право обратиться к куратору. Вы можете попросить зачесть работу или попросить сменить ревьюера.

2023-09-12 18:12 UTC, mccorn commented
@Olegas pr делался так же, как и всё остальные pr. И даже если вы хотите обвинить меня в том, что с этим pr пошло что-то не так, вы же должны были быть первым, кто помог бы разобраться в проблеме. Вместо этого вы послле долгой паузы отмахивались от студента сообщениями там, где с вами даже нельзя связаться и задать уточняющие вопросы. Это по вашему тоже соответствует развитию правильных практик? 

Даже если не всё тесты соответствуют нормальному уровню, в рамках возможностей я сделал достаточно, чтобы показать навык и понимание.

2023-09-12 18:22 UTC, Olegas commented
@mccorn я вас ни в чем не обвиняю.
Я в первом же своем комментарии указал на причину, по которой я вернул ревью. Соглашусь, комментарий про dev-ветку был лишний (т.к. ветка была уже не dev). Возможно это сбило вас с толку. Если так - прошу прощения. 
Так же, видимо, когда во второй раз мы не достигли понимания, мне стоило продублировать комментарий здесь, в PR что бы у вас был канал для обратной связи.
Также хочу заметить, что на ревью есть SLA - 24 часа. На сколько я вижу - этот лимит не был превышен.

2023-09-12 18:29 UTC, mccorn commented
@Olegas вы правда считаете, что дважды сделать ревью на 23+ час воспринимается случайностью. 
Я не принимаю ни ваших извинений, ни ваших субъективных причин не давать апрув. 

Вот почему: представим, что я найду комит со старой версией движка и пересоберу свою ветку, сделав новый чистый пр. А теперь вопрос: нужны ли нам эти формальности?

2023-09-13 08:38 UTC, merged